project:
  type: website

website:
  title: "Xia Zhou"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Publications
        file: publications.qmd

files:
  - publication/**/*.bib

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: false
    page-layout: full