project:
  type: website

website:
  title: "Xia Zhou"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Publications
        href: index.html#publication
      - text: Teaching
        href: index.html#teaching
      - text: CV
        href: pdfs/xz-cv.pdf
      - text: Mobile X Lab
        href: https://mobilex.cs.columbia.edu

files:
  - publication/**/*.*
  - teaching/**/*.*

resources: 
  - images/**
  - pdfs/**

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: false
    page-layout: full